# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46165ed5be2a855eecad6550a8fd045341400e961a0ef3e3662854dd268d56f438ac0a8c010fbcbc3d82a6cd167aad22a53e4edfd322d92c6a2af966072bf3c0

test:
  secret_key_base: b9b49173c3fc54fc2fd791dd365e5489555e3a81d100a2f484662802edba4ea61d7e0ba76bfa6aa3e72a170f1f0c31f216bd5591f7f6c799bc47dbd0277459c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
